Gestion des operations bancaires
liticiakouam/paymybuddy pull request #3
Opened 2023-03-31 17:45 UTC by liticiakouam

- Création de l'interface
- Mise en place de l'API pour lister et sauvegarder les operations
- Gestion de la partie **CREDIT** d'un compte
- Gestion des transactions

2023-04-03 12:01 UTC, valdesekamdem approved these changes
C'est bon.
Après avoir pris en compte mes commentaires. Le code peut être mergé

2023-04-03 12:01 UTC, valdesekamdem commented on src/main/java/com/liticia/paymybuddy/exception/BankAccountNotExistException.java
> +public class BankAccountNotExistException extends RuntimeException{
C'est mieux `BankAccountNotFoundException`

2023-04-03 15:03 UTC, liticiakouam commented on src/main/java/com/liticia/paymybuddy/exception/BankAccountNotExistException.java
> +public class BankAccountNotExistException extends RuntimeException{
D'accord c'est fait

2023-04-04 09:59 UTC, valdesekamdem requested changes

2023-04-04 09:59 UTC, valdesekamdem commented on src/main/java/com/liticia/paymybuddy/Service/BankAccountService.java
> +    List<BankAccount> findActiveAccountNumber(Boolean active);
`findActiveBankAccount`

Et ce n'est pas nécessaire de passer le paramètre `active` car tu dis déjà que ce sont les comptes actifs que tu veux récupérer.

2023-04-04 09:59 UTC, valdesekamdem commented on src/main/java/com/liticia/paymybuddy/Service/impl/BankAccountServiceImpl.java
> +        return bankAccountRepository.findByActive(active);
Si tu te passes tu paramètre comme j'ai mentionné au niveau de l'interface, ici tu peux directement faire 
`return bankAccountRepository.findByActive(true);`

2023-04-04 09:59 UTC, valdesekamdem commented on src/main/java/com/liticia/paymybuddy/Service/impl/OperationServiceImpl.java
> +    public void saveCreditedAccount(OperationCreate operationCreate) {
`saveCreditedAccount` --> `creditAccount`

2023-04-04 09:59 UTC, valdesekamdem commented on src/main/java/com/liticia/paymybuddy/Service/impl/OperationServiceImpl.java
> +    public void saveCreditedAccount(OperationCreate operationCreate) {
Aussi, si tu sépares le credit du debit, alors plutôt que de passer `OperationCreate` et tester si c'est un CREDIT, tu peux directement passer `accountNumber` et `amount` en paramètre. C'est celui qui appelle cette méthode (le controller) qui va se charger de la condition (si c'est CREDIT ou DEBIT) et appeler la méthode correspondante, d'ailleurs c'est ce que tu as fait au niveau du controller.

2023-04-04 09:59 UTC, valdesekamdem commented on src/main/java/com/liticia/paymybuddy/Service/impl/OperationServiceImpl.java
> +    public void saveDebitedAccount(OperationCreate operationCreate) {
`saveDebitedAccount` --> `debitAccount`

2023-04-04 09:59 UTC, valdesekamdem commented on src/main/java/com/liticia/paymybuddy/Service/impl/OperationServiceImpl.java
> +    public void saveDebitedAccount(OperationCreate operationCreate) {
Pareil ici, tu passes directement le `accountNumber` et le `amount`

2023-04-04 09:59 UTC, valdesekamdem commented on src/main/java/com/liticia/paymybuddy/controller/OperationController.java
> +           operationService.saveDebitedAccount(operationCreate);
Tu mets ceci dans un 
`else if (operationCreate.getOperationType() == OperationType.DEBIT)` afin d'éviter que di demain tu ajoutes un autre type d'opération que ça fasse toujours le DEBIT

2023-04-04 18:11 UTC, merged