Gestion des transferts d'argent
liticiakouam/paymybuddy pull request #6
Opened 2023-04-12 16:49 UTC by liticiakouam

- afficher la liste des transactions
- sauvegarder une transaction

2023-04-12 17:37 UTC, valdesekamdem requested changes

2023-04-12 17:37 UTC, valdesekamdem commented on src/main/resources/templates/contact.html
> +              <a class="text-decoration-none badge rounded-pill bg-secondary me-3" th:href="@{/contact/find/{id}(id=${contact.id})}">Transfer Money</a>
Pourquoi ne pas directement appeler le endpoint pour le transfert vers un contact ici ? Celui-ci `transaction/contact?contactId...` 
Aller vers le ContactController avant de rediriger vers les transaction est inutile.

2023-04-12 17:37 UTC, valdesekamdem commented on src/main/java/com/liticia/paymybuddy/controller/ContactController.java
> +    public String findContactById (@PathVariable(value = "id") long id) {
Si la redirection est bien implémentée au niveau de la vue, tu n'as pas besoin de ceci.
C'est un endpoint inutile. Il ne fait que la redirection.

2023-04-12 17:37 UTC, valdesekamdem commented on src/test/java/com/liticia/paymybuddy/repository/ContactRepositoryTest.java
> +    void testShouldDeleteContact() {
Dans ce test, qu'est ce qui confirme que le contact a bien été supprimé ?
Il faut rajouter une vérification du nom de contact dans la base de données après avoir appelé le `deleteById`

2023-04-12 17:37 UTC, valdesekamdem commented on src/main/java/com/liticia/paymybuddy/Entity/Transaction.java
> +    @DateTimeFormat(pattern = "yyyy-MM-dd")
Ce serait intéressant d'avoir l'heure de la transaction aussi, je pense.

2023-04-12 19:51 UTC, liticiakouam commented on src/main/java/com/liticia/paymybuddy/Entity/Transaction.java
> +    @DateTimeFormat(pattern = "yyyy-MM-dd")
D'accord je t'ai lu et j'ai tenu compte de toute tes modifications

2023-04-12 19:52 UTC, liticiakouam commented on src/main/resources/templates/contact.html
> +              <a class="text-decoration-none badge rounded-pill bg-secondary me-3" th:href="@{/contact/find/{id}(id=${contact.id})}">Transfer Money</a>
OK

2023-04-13 08:46 UTC, valdesekamdem approved these changes

2023-04-13 13:34 UTC, merged